" NERDTree 配置
" 在 vim 启动的时候默认开启 NERDTree（autocmd 可以缩写为 au）
autocmd VimEnter * NERDTree
" 按下 F3 调出/隐藏 NERDTree
" map :silent! NERDTreeToggle
map <F3> :NERDTreeMirror<CR>
map <F3> :NERDTreeToggle<CR>

" 将 NERDTree 的窗口设置在 vim 窗口的右侧（默认为左侧）
let NERDTreeWinPos="left"
" 当打开 NERDTree 窗口时，自动显示 Bookmarks
let NERDTreeShowBookmarks=0
" 不显示帮助面板"
let NERDTreeMinimalUI=1
" set foldmethod=indent
